apiVersion: apps/v1
kind: Deployment
metadata:
  name: pmu-version-deployment
  labels:
    app: pmu-version
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pmu-version
  template:
    metadata:
      labels:
        app: pmu-version
    spec:
      containers:
      - name: pmu-version
        image: pmu-version:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
